name: Service Status Check

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up bash
      run: chmod +x status/status_monitor.sh
    
    - name: Run status check
      run: ./status/status_monitor.sh
    
    - name: Deploy status page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./status
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'